name: Deploy MkDocs Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocstrings mkdocstrings[python]

    - name: Build the documentation
      run: mkdocs build --clean

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  
        publish_dir: ./site
        user_name: 'GitHub Actions'
        user_email: 'github-actions[bot]@users.noreply.github.com'